name: Build

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get short SHA
        id: short-sha
        run: |
          if [ $ACTION = opened ]; then
              # we have to get the head sha directly from the pr api, because github silly ig
              echo "then"
              sha=$(wget -O- --quiet https://api.github.com/repos/LemLib/LemLib/pulls/$PR_NUM | jq -r .head.sha | head -c 6)
          else
              echo "else"
              sha=$(echo $SHA | head -c 6)
          fi
          echo "sha=$sha" >> $GITHUB_OUTPUT
        env:
          SHA: ${{ github.event.after }} # this isn't present for pr opened events
          ACTION: ${{github.event.action}}
          PR_NUM: ${{github.event.number}}

      - name: Set short SHA
        run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}

      - name: Install ARM Toolchain
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: "10-2020-q4"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: PIP Installer
        uses: BSFishy/pip-action@v1
        with:
          packages: pros-cli

      - name: Testing PROS Install
        run: pros --version

      - name: Clean
        run: pros make clean

      - name: Clean
        run: pros make

     
